In [77]:
from sklearn import datasets, tree
import numpy as np
import pandas  as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
iris = datasets.load_iris()

In [46]:
x,y= iris.data[:, :2],  iris.target
x_train,x_test, y_train,y_test = train_test_split(x,y,test_size=0.3, random_state =0)

In [48]:
x = iris.data
y = iris.target

In [49]:
from sklearn.preprocessing import StandardScaler

In [50]:
scaler = StandardScaler().fit(x)


In [51]:
model = tree.DecisionTreeClassifier(criterion = 'entropy', random_state = 0)

In [52]:
model.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [58]:
#generating evaluation matrix

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print('TrainAccuracy:', accuracy_score(y_train, model.predict(x_train)))
print('TrainConfusionMatrix:',confusion_matrix(y_train,model.predict(x_train)))
      

TrainAccuracy: 0.9428571428571428
TrainConfusionMatrix: [[34  0  0]
 [ 0 32  0]
 [ 0  6 33]]


In [64]:
print('TestAccuracy:', accuracy_score(y_test, model.predict(x_test)))
print('TestConfusionMatrix:',confusion_matrix(y_test,model.predict(x_test)))
print('TestClassificationReport:', classification_report(y_test,model.predict(x_test)))


TestAccuracy: 0.6444444444444445
TestConfusionMatrix: [[16  0  0]
 [ 1 10  7]
 [ 0  8  3]]
TestClassificationReport:               precision    recall  f1-score   support

           0       0.94      1.00      0.97        16
           1       0.56      0.56      0.56        18
           2       0.30      0.27      0.29        11

    accuracy                           0.64        45
   macro avg       0.60      0.61      0.60        45
weighted avg       0.63      0.64      0.64        45



In [78]:
sns.heatmap(classification_report(y_test,model.predict(x_test)), cmap ='RdBu_r', annot=True, fmt ='2f', vmin=-1, vmax=1)
plt.show()

ValueError: Must pass 2-d input. shape=()

In [ ]:
from sklearn.externals.six import StringIO
import pydot
out_data = StringID()
tree.export_gravpviz(clf, out_file  = out_data, feature_names = model.classes_.astype(int).astype(str),filled = True, rounded= True,
                     special_characters=True, node_id=1,)
graph = pydot.graph_fromdot_data(out_data.getvalue())